### PR TITLE
return proper json response headers, fix system.js to handle that

### LINKED ISSUE #17: Improve repsonse header
We should use  `Content-Type: application/json; charset=utf-8` for JSON Responses.
May we're able to only accept `application/json` responses.

We should remove this from header: `x-powered-by PHP/5.5.9-1ubuntu4.14`

### PR DESCRIPTION
**Pull request by CapCalamity**
closes #17

### CODE REVIEW

**Comment by iPaat** [comment]
common.ajax without proper header still used:
https://github.com/CapCalamity/perfmon/blob/enhancement/jsonheaders/app/Http/routes.php#L98-L100
https://github.com/CapCalamity/perfmon/blob/enhancement/jsonheaders/app/Http/routes.php#L110-L113
https://github.com/CapCalamity/perfmon/blob/enhancement/jsonheaders/app/Http/routes.php#L134-L137

missing content-type & status code

**Comment by CapCalamity** [comment]
Shouldn't have opened that pull-request in such a hurry...
Will update those tomorrow, although i think we can remove the `pingback` entirely... #21

**Comment by CapCalamity** [comment]
#21

**Comment by iPaat** [comment]
Looks good to me now.

**Pull request merged**
