### PR TITLE
add basic formatter function for tooltips

### PR DESCRIPTION
**Pull request by CapCalamity**
please review functions for possibly more efficient or more expressive ways

### CODE REVIEW

**Comment by CapCalamity** [comment]
NetIO doesn't have enhanced tooltips... will fix

**Comment by iPaat** [comment]
NetIO packets graph comes with byte formatter.
The others seem to be okay. Functions are okay in my opinion as well.

**Comment by CapCalamity** [comment]
You're right... Also saw that there were too many Series' in the graphs. 
I will just fix that in this PR

**Comment by iPaat** [comment]
Works for me now.

**Pull request merged**
